### ISSUE TITLE
request parameter

### ISSUE THREAD

**Issue by lordmen99** [UrielCh/midjourney-client#1]
hi, what must add in request.txt ?

**Comment by lordmen99** [comment]
its already describe function?

**Comment by UrielCh** [comment]
```js
fetch("https://discord.com/api/v9/interactions", {
  "headers": {
    "accept": "*/*",
    "accept-language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,he;q=0.6",
    "authorization": "XXXXXX",
...
...
```

Just copy past the fetch request.
Internally I only use `guild_id` `channel_id`, `session_id` and of course the `authorization` secret.

I'm trying to add an extra Discord bot within the client to speed up all calls.
