### ISSUE TITLE
I cannot obtain the client correctly using these two types of construction. May I know how to obtain the client

### ISSUE THREAD

**Issue by l269438** [UrielCh/midjourney-client#14]
![image](https://github.com/UrielCh/midjourney-client/assets/48855839/2283b6ca-9693-48ca-a1e2-e555f49d67ef)
![image](https://github.com/UrielCh/midjourney-client/assets/48855839/2c91322f-99fa-4755-8dd0-ea7603f0e253)

**Comment by UrielCh** [comment]
I already support to much different authentification method.

downloading a interaction.txt file is not one of them.

please download interaction.txt to a local file and use it directly.
