### ISSUE TITLE
Hi, I'm not getting a promise from the function, what could be the problem?

### ISSUE THREAD

**Issue by Dr-Alex-Dr** [UrielCh/midjourney-client#15]
![Снимок экрана 2023-06-08 152450](https://github.com/UrielCh/midjourney-client/assets/60229705/2733dae7-a95b-4fc4-bd45-8c870a360e62)
![Снимок экрана 2023-06-08 155042](https://github.com/UrielCh/midjourney-client/assets/60229705/f0224d26-5b11-4f2c-9898-94e52c976e82)

**Comment by UrielCh** [comment]
maybe the promise had been resolved by the await ...
