### ISSUE TITLE
Deps are not loaded

### ISSUE THREAD

**Issue by zcode-apps** [UrielCh/midjourney-client#16]
Hey,

i've freshly installed the package in a clear folder.
After i setup the .env, i got the error that node-fetch is not installed, when i will get the latest msgs.
When i use the code to send a prompt to my server/channel, than i got the error that WebSocket is not definied?

here is my code:

```
import Midjourney from "midjourney-discord-api";

const client = new Midjourney(".env");
await client.connectWs(); // Used Websocket to boost detection. (experiental)
const msg = await client.imagine(
  "A photo of an astronaut riding a horse", 
  /* add optional progress function (percent) => void */
);
console.log("you find your result here: ", msg.attachments[0].url);
```

**Comment by UrielCh** [comment]
the project code itself is built onto deno.

your question is out of scope.
