### ISSUE TITLE
not found library

### ISSUE THREAD

**Issue by lordmen99** [UrielCh/midjourney-client#2]
macpro@Macs-MacBook-Pro server % npm install midjourney-discord-api
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/midjourney-discord-api - Not found
npm ERR! 404 
npm ERR! 404  'midjourney-discord-api@*' is not in this registry.

**Comment by UrielCh** [comment]
for now I only test my code with deno :)

**Comment by UrielCh** [comment]
You tried to install it before `npmJS` had time to upload the package onto its CDN.

You are the first.

I just tested with `index.mjs`
```javascript
import Midjourney from "midjourney-discord-api";

async function main() {
    const cli = new Midjourney('interaction.txt');
    const msgs = await cli.getMessages();
    console.log(msgs.length + ' message visible');
}

main();
```
and it works. (once an `interaction.txt` file is present)
