### ISSUE TITLE
Support for turbo mode

### ISSUE THREAD

**Issue by d400800** [UrielCh/midjourney-client#21]
I faced an issue with the imagine method when using the turbo mode. I managed to fix it by overriding some of the methods in the Midjourney and DiscordMessage classes. Here are the changes I made to make it work:

Midjourney.filterMessages:
`matches = matches.filter((item) => item.prompt)` -> `matches = matches.filter((item) => item.prompt || item.content);`
`const itemPrompt = item.prompt.prompt;` -> `const itemPrompt = (item.prompt && item.prompt.prompt) || getPromptFromContent(item.content);`

Where getPromptFromContent is:
`function getPromptFromContent(content) {
    return content.match(regEx) ? content.match(regEx)[1] : '';
}`

Midjourney.followCheckMsg:
`const prompt = msg.prompt;` -> `const prompt = msg.prompt || msg.content;`

the extractPrompt function inside the DiscordMessage file (not a class member) I added:
`if (extra.endsWith(' (turbo)')) {
      result.mode = 'fast';
      extra = extra.substring(0, extra.length - 8);
  }`

Not sure about `result.mode = 'fast';` here, but it works.

**Comment by UrielCh** [comment]
turbo mode ... what that ?

**Comment by UrielCh** [comment]
<img width="702" alt="Screenshot 2023-07-18 at 10 50 53" src="https://github.com/UrielCh/midjourney-client/assets/6543761/49d75fd0-d89f-4e59-b945-7ff1692887af">

okey... lewt's tryed out

**Comment by d400800** [comment]
It is a newly added image generation mode that Midjourney issued recently. It generates images very fast.
https://docs.midjourney.com/docs/fast-relax

**Comment by UrielCh** [comment]
copy and past here the error message displayed in your terminal:

the errors are generated by this 2 log lines:
```ts
    logger.warn(`Failed to extract prompt data from: ${pc.yellow(content)}`);
    logger.warn(`Extra data:"${pc.yellow(extra)}"`);
```

**Comment by d400800** [comment]
2023-07-18 10:59:04 Warn: Failed to extract prompt data from: **hot trends low prices every single day, in the style of candid, saturated hues , ecommerce website selling fashion products, pink, blue colors --turbo --ar 16:9 
--q .75 --no text fonts letters watermark words typography slogans signature** - <@1115263101697265724> (turbo)
2023-07-18 10:59:04 Warn: Extra data:"**hot trends low prices every single day, in the style of candid, saturated hues , ecommerce website selling fashion products, pink, blue colors --turbo --ar 16:9 --q .75 --no text fonts 
letters watermark words typography slogans signature** - <@1115263101697265724> (turbo)

**Comment by UrielCh** [comment]
Turbo support added.

**Comment by d400800** [comment]
Thanks!

**Comment by UrielCh** [comment]
just commited, but not available published to npmjs yet.

can you try the current git version ?

**Comment by d400800** [comment]
Sure, I'll try it now.

**Comment by d400800** [comment]
לא מצליח לשנות את הווסטאפ שלי. אתה יכול לרשום לי את המספר שלך ל-d400801@gmail.com?

**Comment by UrielCh** [comment]
Stay on E-mail for now.

**Comment by UrielCh** [comment]
v 1.0.6 is out
