### ISSUE TITLE
worked once, then failed

### ISSUE THREAD

**Issue by madc0w** [UrielCh/midjourney-client#26]
The reason being that the token provided has a 24-hour lifespan. Refreshing this token manually every day is not a prod solution.
Is there any way to exchange this user token for a long-lived one?

**Comment by UrielCh** [comment]
I stopped paying for my MidJourney account, so I cannot proceed with any development for now.

If you'd like to offer me a month of MidJourney, I can integrate a new OAuth and update the project. Alternatively, you could allow me to use an existing account. Up until now, I had borrowed my wife's account to build the library.

**Comment by devranerogul** [comment]
I can provide you an account.
