### ISSUE TITLE
INTERACTION_APPLICATION_COMMAND_INVALID_VERSION when I call imagine function

### ISSUE THREAD

**Issue by LucasEscavia** [UrielCh/midjourney-client#29]
Hello,

I have issue trying to use the imagine function to generate a image, the function return this error : 
Error Midjourney Error: imagine return 400 Bad Request {"message": "Corps de formulaire non valide", "code": 50035, "errors": {"data": {"_errors": [{"code": "INTERACTION_APPLICATION_COMMAND_INVALID_VERSION", "message": "D\u00e9lai d\u00e9pass\u00e9 pour cette commande, r\u00e9essaie dans quelques minutes"}]}}}

It worked a few weeks ago but since 1 week I can't make it work.

I tried to generate another interaction file but I'm still facing the same issue, is it a bug ? Do you have a solution ?

Thanks.

**Comment by devranerogul** [comment]
Same issue... Any news?

**Comment by devranerogul** [comment]
@LucasEscavia found a solution. Delete imagine.json file in cmdCache folder. It caches command and stores values, but It seems it should change after you change interactions file.

**Comment by LucasEscavia** [comment]
Hi, thanks a lot @devranerogul, I was really struggling with that, and now it works perfectly.
