### ISSUE TITLE
WebSocket not defined but used (Node.js Mac ARM)

### ISSUE THREAD

**Issue by Brusdeylins** [UrielCh/midjourney-client#31]
WebSocket is used, but not imported ?!

ERROR:
/Users/.../node_modules/midjourney-discord-api/script/src/Midjourney.js:259
        this.ws = new WebSocket("wss://gateway.discord.gg/?encoding=json&v=9");
                      ^

ReferenceError: WebSocket is not defined
    at Midjourney.connectWs (/Users/.../node_modules/midjourney-discord-api/script/src/Midjourney.js:259:23)
    ...

RUNTIME: 
Node.js v18.14.1 (MAC ARM)

YOUR CODE:
async connectWs() {
        if (this.ws && this.wsActivated) {
            return;
        }
        let heartbeat_interval = 10000;
        this.ws = new WebSocket("wss://gateway.discord.gg/?encoding=json&v=9");
        ....                   ^

and there is no Import of a WebSocket Class in Midjourney.js / .ts  (version 1.0.6)

Greetings.

**Comment by UrielCh** [comment]
The code in this repo, use Deno, to WebSocket do not need to be import.

the nodeJS version is built by the dnt lib, and import all missing l,ibs to make it works.

1- use up to date nodeJS, or use deno.

**Comment by UrielCh** [comment]
Try With NodeJS 20
