### ISSUE TITLE
unknown integration error

### ISSUE THREAD

**Issue by apekris** [UrielCh/midjourney-client#32]
```
node_modules\midjourney-discord-api\script\src\Midjourney.js:457
        throw new Error(`imagine return ${response.status} ${response.statusText} ${await response.text()}`);
              ^

Error: imagine return 400 Bad Request {"message": "Unknown Integration", "code": 10005}
    at Midjourney.imagine (C:\Users\apekr\gpt\node_modules\midjourney-discord-api\script\src\Midjourney.js:457:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by UrielCh** [comment]
Hello, my Midjourney subscription has been terminated. If you need me to fix any errors, please provide me with access privately, and I will be able to address them. I'm unable to maintain subscriptions to all the current AI platforms.

**Comment by just-inn** [comment]
Hello Uriel, I am running into exactly the same error recently.

Should i expect it to be fixed in the library's code, or would it be better to contact you directly? 

Immensely thankful for  providing us with the library!

**Comment by apekris** [comment]
I think it may be related to this line with a hard-coded bot id
```
this.application_id = "936929561302675456";
```

I suspect the bot with this ID has now been removed, I guess not surprising since @UrielCh mentioned their account is terminated

**Comment by UrielCh** [comment]
I can fix it with an account.

**Comment by UrielCh** [comment]
note:
`application_id = "936929561302675456"`
is the id of the discord web client, not my Id.

**Comment by apekris** [comment]
Any hints for how we can debug this? The error seems to indicate an unrecognized (bot?) `id` of some sort 🤔 Their application ID has all the appropriate permissions to interact, including direct private msgs, etc.

**Comment by UrielCh** [comment]
WIP

**Comment by UrielCh** [comment]
V 1.0.8 is out

**Comment by UrielCh** [comment]
fixed
