### ISSUE TITLE
imagine await stuck

### ISSUE THREAD

**Issue by n1m4mz** [UrielCh/midjourney-client#35]
hello hope you are doing well,

I've encountered an issue with this :

const msg = await client.imagine('');

seems sometime(most) the promise wont resolve and the program will stuck there, also nothing will output on console.

**Comment by n1m4mz** [comment]
message will send to the discord, after that nothing happening, it will stuck there.

**Comment by UrielCh** [comment]
imagine with an empty prompt ??

**Comment by n1m4mz** [comment]
No, I will fill in this line. As mentioned, the 'imagine' function is working fine, and the message will successfully send to Discord. However, it seems to get stuck here after that. Sometimes it works well (logging everything properly), but other times it just sends the message and nothing happens (also, no logging for image creation progress). I have no idea what's wrong. I think in certain conditions, it won't resolve or reject.

**Comment by UrielCh** [comment]
Send me a sample code to reproduce the issue, that should come from the prompt, some prompt are rewiten by midjourney.

I have some custom handler for that some type of rewriting, this one may not be supported.

**Comment by n1m4mz** [comment]
I'm just using your sample:

import Midjourney from "midjourney-discord-api";

const client = new Midjourney("interaction.txt");
await client.connectWs(); // Using WebSocket to boost detection. (experimental)
const msg = await client.imagine(
  "A photo of an astronaut riding a horse", 
  /* add optional progress function (percent) => void */
);
console.log("You can find your result here:", msg.attachments[0].url);


Here, the console log will not be called no matter how long I wait.

**Comment by UrielCh** [comment]
juste tested:

```bash
mkdir aaa
cd aaa
cp ../midjourney-client/interaction.txt .
```

fill aaa.ts with:
```ts
import Midjourney from "npm:midjourney-discord-api";

const client = new Midjourney("interaction.txt");
await client.connectWs(); // Using WebSocket to boost detection. (experimental)
const msg = await client.imagine(
"A photo of an astronaut riding a horse",
/* add optional progress function (percent) => void */
);
console.log("You can find your result here:", msg.attachments[0].url);
```

```bash
deno run -A aaa.ts 
```

the script run, and did not closed:
```
2024-05-20 18:13:49 Info: wait for the prompt in Queue
2024-05-20 18:13:49 Info: follow message completion: (0%)
2024-05-20 18:13:56 Info: follow message completion: (15%)
2024-05-20 18:13:57 Info: follow message completion: (31%)
2024-05-20 18:13:58 Info: follow message completion: (46%)
2024-05-20 18:13:58 Info: follow message completion: (62%)
2024-05-20 18:13:59 Info: follow message completion: (78%)
2024-05-20 18:14:00 Info: follow message completion: (93%)
2024-05-20 18:14:02 Info: waitMessage found a 100% process done message
You can find your result here: https://cdn.discordapp.com/attachments/XXXXX/XXXXXX/rosalbus_A_photo_of_an_astronaut_riding_a_horse_bdf4665c-9b3a-4858-81e5-b7e09f8f2287.png....
```

you should add a client.disconnectWs() at the end to let the sample code close.

**Comment by UrielCh** [comment]
just tested with the extra `client.disconnectWs()` the sample closed at the end.

**Comment by n1m4mz** [comment]
I believe I've identified the problem. Here's the situation: I want to generate certain commands multiple times, for example, 10 times. However, when I attempt to do this either in a loop or by manually re-entering the same prompt, I encounter this error in the console:

"Error: Warning! Multiple messages match your waiting request. Please review your criteria: {
progress: [Function (anonymous)],
interaction: 'imagine',
prompt: 'A photo of an astronaut riding a horse',
startId: '1242154096610246656',
maxWait: 3000
}"

I suspect that due to internal processes, the system interprets my new prompt as having the same ID as the previous one. Consequently, it doesn't display the logging because it's already completed. What would be the correct approach to resolve this?

**Comment by UrielCh** [comment]
if you want to generate multiple time the same prompt, provide an explicite seed in the request.
