### ISSUE TITLE
Question：Discord user-client Interactions

### ISSUE THREAD

**Issue by Whitedragon115** [UrielCh/midjourney-client#36]
Hello, I am very confuse how to you make discord Slash-Command interaction works, I have try so many ways and search so many information, but I still can't understand how discord interactions works, can you tell me or highlight where do you post the interaction and how do you get the data it send back! thank you!

**Comment by Whitedragon115** [comment]
figure it out, you are using DM to send the commands, that is so smart

well, Im looking for the server command interactions, there is like so many other internet technology in it...
thanks man!

**Comment by UrielCh** [comment]
have you some more questions ?

**Comment by Whitedragon115** [comment]
yeah kinda of...
I don't know how do you get the response from the interaction message

**Comment by UrielCh** [comment]
no question about the project.
