### ISSUE TITLE
client.imagine is not get back any results 

### ISSUE THREAD

**Issue by LKR-MANOFIT** [UrielCh/midjourney-client#38]
```
import Midjourney from "midjourney-discord-api";
const client = new Midjourney("interaction.txt");
const msg = await client.imagine(
  "Harry Potter and the Prisoner of Azkaban cover");
console.log(msg);
```
noting happend only i ge this 2 message on console:
``` waitMessage 1st request gets 1 messages, Will retry one per sec up to 3000 times```
after generation complete:
```  waitMessage 90th request gets 1 messages ```
this code was work yesterday but today is suddenly stop working.

**Comment by vladgardus** [comment]
Same thing happens to me. 

Also, if I try to connect to use the `client.connectWs();` method, the imagine method is still stuck but I do not get the two waitMessage logs above.

**Comment by Prajval108** [comment]
In my case, the response is getting stuck in between, although the image is generated by the Midjourney bot in Discord Just library stop listening the events it seems.


2024-09-10 11:22:54 Info: wait for the prompt in Queue
2024-09-10 11:22:54 Info: waitMessage 1500th request gets 1 messages
2024-09-10 11:23:00 Info: follow message completion: (0%)
2024-09-10 11:23:02 Info: follow message completion: (10%)
2024-09-10 11:23:05 Info: follow message completion: (15%)
2024-09-10 11:23:08 Info: follow message completion: (22%)
2024-09-10 11:23:13 Info: follow message completion: (30%)
2024-09-10 11:23:15 Info: follow message completion: (32%)
2024-09-10 11:23:18 Info: follow message completion: (35%)
2024-09-10 11:23:22 Info: follow message completion: (45%)
2024-09-10 11:23:25 Info: follow message completion: (65%)
2024-09-10 11:23:30 Info: follow message completion: (85%)
2024-09-10 11:23:31 Info: waitMessage 1367th request gets 1 messages
2024-09-10 11:23:31 Info: waitMessage 1937th request gets 1 messages

**Comment by UrielCh** [comment]
ok ok, let me fix that...

**Comment by UrielCh** [comment]
I have just start progressLogger.ts the "Harry Potter and the Prisoner of Azkaban cover" prompt and it works.

can you provid a code sample that fail ?

**Comment by Prajval108** [comment]
It appears that a particular prompt is experiencing an issue.
 You can try the following prompt:

**A professional setting featuring a diverse group of tech experts working collaboratively in a modern office. Emphasize the themes of innovation and agility in technology. Show elements of AI and Blockchain, like holographic displays, digital interfaces, and data analytics. Display a futuristic and dynamic atmosphere, showcasing teamwork and cutting-edge technology in North America. Ensure the setting is sleek and high-tech, with a focus on business transformation and innovation.**

**Comment by Prajval108** [comment]
> It appears that a particular prompt is experiencing an issue. You can try the following prompt:
> 
> **A professional setting featuring a diverse group of tech experts working collaboratively in a modern office. Emphasize the themes of innovation and agility in technology. Show elements of AI and Blockchain, like holographic displays, digital interfaces, and data analytics. Display a futuristic and dynamic atmosphere, showcasing teamwork and cutting-edge technology in North America. Ensure the setting is sleek and high-tech, with a focus on business transformation and innovation.**

Although Discord is showing a generated image, the library is not listing any events; it seems.
