### ISSUE TITLE
await msg.upscale(i) gets stuck 

### ISSUE THREAD

**Issue by mini-peanut** [UrielCh/midjourney-client#39]
The method `msg.upscale(i)` gets stuck without returning anything, without interrupting, and without throwing any error, even though MidJourney has successfully generated the image.

**Comment by UrielCh** [comment]
I need to add a new regexp to fix that.

**Comment by UrielCh** [comment]
I have juste try the script `upscaleLast.ts` that upscall the last image, and it works.
provide a code sample to cause the error, it you want a fix.
