### ISSUE TITLE
upscale by messageid image

### ISSUE THREAD

**Issue by lordmen99** [UrielCh/midjourney-client#4]
add upscale by message id after generate please. i try use getmessagebyid its looks like cant upscale. 
```ts
const msgs2 = await cli.getMessages();
const msgs = await cli.getMessageById(msgs2.id);
main:
for (const msg of msgs) {
  if (!msg.canUpscale()) {
    continue;
  }
  for (let i = 1; i <= 4; i++) {
    if (msg.canUpscale(i)) {
      console.log(`Upscaling image ${i} from ${msg.id}: ${msg.prompt?.prompt}`);
      const result = await msg.upscale(i);
      await result.download(0, "images");
      break main;
    }
  }
}
```
so let say after generate image, in next hours user want upscale that image can easy doing with that message id then choose U1,U2 or else. after that user can get upscaled image

**Comment by lordmen99** [comment]
sm/src/Midjourney.js:468
            const strValue = value.toString();
                                   ^

TypeError: Cannot read properties of undefined (reading 'toString')

**Comment by UrielCh** [comment]
`const msgs2 = await cli.getMessages();` return an array.
so `msgs2.id` is incorrect.
msgs2[0].id can work if at least one message exists.

`const msgs = await cli.getMessageById(msgs2.id);`
will return a single message not a list ...

Could you correct your code first?

**Comment by lordmen99** [comment]
> `const msgs2 = await cli.getMessages();` return an array. so `msgs2.id` is incorrect. msgs2[0].id can work if at least one message exists.
> 
> `const msgs = await cli.getMessageById(msgs2.id);` will return a single message not a list ...
> 
> Could you correct your code first?

still not working

`for (const msg of msgs) {
                  ^

TypeError: msgs is not iterable`

you have got what i mean, in this "so let say after generate image, in next hours user want upscale that image can easy doing with that message id then choose U1,U2 or else"

**Comment by UrielCh** [comment]
retry to write your script based on the sample:

https://github.com/UrielCh/midjourney-client/blob/main/samples/upscaleLast.ts

**Comment by UrielCh** [comment]
a new sample:
```ts
import { Midjourney } from "../mod.ts";
import { SnowflakeObj } from "../mod.ts";

/**
 * Upscale all withing the 20 last images generated 2 hours ago
 */
const client = new Midjourney("interaction.txt");
const snowflake = new SnowflakeObj(-2 * 60 * 60 * 1000);
// or select the exact time
// snowflake.timestamp = new Date('2023-05-03T05:03:34.593Z').getTime();
const msgs = await client.getMessages({after: snowflake.encode(), limit: 20});

for (const msg of msgs) {
  if (!msg.canUpscale()) {
    continue;
  }
  for (let i = 1; i <= 4; i++) {
    if (msg.canUpscale(i)) {
      console.log(`Upscaling image ${i} from ${msg.id}: ${msg.prompt?.prompt}`);
      const result = await msg.upscale(i);
      await result.download(0, "images");
    }
  }
}
```

**Comment by lordmen99** [comment]
for upscaling its ok.  for describe  i get some issue too when run Describe, i am run on my server.  here is :

r/node_modules/midjourney-discord-api/script/src/utils.js:33
    const data = await (await fetch(url)).arrayBuffer();
                 ^
ReferenceError: fetch is not defined

**Comment by UrielCh** [comment]
use nodeJS 18+

**Comment by lordmen99** [comment]
how to get progress completion bro? i want after generate, i can log progrress from 0% until 100% in realtime

**Comment by UrielCh** [comment]
Progression messages are sent as private messages, I do not know how to get those messages using discord web calls.

**Comment by lordmen99** [comment]
i see can use grap from. content value. its have percentage changes second by second. sample =

"content": "**A hyperrealistic photograph by Andreas Gursky of a gas station at night. Portrait format, front view with a high vantage point. The station should occupy the center of the frame, with a line of cars waiting to refuel on the left. Floodlights should illuminate the scene, casting harsh shadows on the ground. The station should have a modern design with clean lines and bold colors. The cars should be mostly black or white, with occasional red or blue accents. Post-processing should emphasize the station's artificiality and the stark contrast between light and shadow. --v 5 --ar 2:3 --s 800 --chaos 10** - <@1099895049405353985> (15%) (fast)",

grap 15% in (). then doing read every 3 second to get this progress percentage

**Comment by UrielCh** [comment]
I have just found it: wss://gateway.discord.gg/?encoding=json&v=9
it's looks easy to use.

**Comment by lordmen99** [comment]
> I have just found it: wss://gateway.discord.gg/?encoding=json&v=9 it's looks easy to use.

what is this?

**Comment by UrielCh** [comment]
a new version is out.

**Comment by lordmen99** [comment]
how about progress completion? how i can add on log after send cmd /imagine.

**Comment by UrielCh** [comment]
The previous version fixes some errors in waiting for results.

I did not yet implement the progress bar for the function that sent their progression as a private message (ephemeral messages that can only be seen by a single person).

and the `/blend` is now implemented.

**Comment by lordmen99** [comment]
i mean for /imagine. how get progress generate. i want try make first console.log. but sstill cant get it

**Comment by lordmen99** [comment]
and how get this log =

Info: interaction Name:  imagine {

cause i see after send command imagine, its will pool every second to get progress generate

**Comment by UrielCh** [comment]
check V0.2.0
