### ISSUE TITLE
After getting an error on Discord, you might not be able to receive response messages, which is probably due to a disconnection from the Discord server. You can try reconnecting or waiting for a while before attempting again. If the problem persists, you may need to contact the Discord support team for further assistance.

### ISSUE THREAD

**Issue by NameQuChen** [UrielCh/midjourney-client#6]
After getting an error on Discord, you might not be able to receive response messages, which is probably due to a disconnection from the Discord server. You can try reconnecting or waiting for a while before attempting again. If the problem persists, you may need to contact the Discord support team for further assistance.

**Comment by UrielCh** [comment]
context ?

**Comment by NameQuChen** [comment]
Prohibited words appear，The process will get stuck

**Comment by UrielCh** [comment]
so it's fixed ?

**Comment by lordmen99** [comment]
have test latest version show this : 

      throw new Error(`imagine return ${response.status} ${response.statusText} ${await response.text()}`);
              ^


Error: imagine return 400 Bad Request {"message": "Unknown Application", "code": 10002}

its use imagine sample

**Comment by UrielCh** [comment]
Stange it works on my config, Les me restore the old application id.

**Comment by UrielCh** [comment]
yep I found the error.

**Comment by UrielCh** [comment]
it's fixed in 1.0.1, but please do not abuse midjourney.

**Comment by NameQuChen** [comment]
thank you

**Comment by NameQuChen** [comment]
> 所以它是固定的？

yes
