### ISSUE TITLE
get progress..

### ISSUE THREAD

**Issue by lordmen99** [UrielCh/midjourney-client#7]
Hi, how get progress after send generate, try get this log :

I2023-05-12 08:29:31 Info: interaction Name:  imagine {
  prompt: 'An editorial style photograph of the most beautiful 21 years physical attractive Indonesia Asian woman alive, dramatic and stunning award winning photo, dramatic linear delicacy, shot on Sony aiii high resolution digital camera, hyper realistic skin, tanned, global illumination, very natural features, TIME cover photo, f/11 --uplight --ar 2:3 --q 2 --v 5.1',
  source: '**An editorial style photograph of the most beautiful 21 years physical attractive Indonesia Asian woman alive, dramatic and stunning award winning photo, dramatic linear delicacy, shot on Sony aiii high resolution digital camera, hyper realistic skin, tanned, global illumination, very natural features, TIME cover photo, f/11 --uplight --ar 2:3 --q 2 --v 5.1** - <@1099895049405353985> (93%) (fast)',
  name: '',
  mode: 'fast',
  id: '1099895049405353985',
  completion: 0.93,
  type: 'grid'

**Comment by UrielCh** [comment]
I had rewritten this part of the code, but mid-journey looks very slow today, It's hard to test it now.

**Comment by lordmen99** [comment]
nice,  i will try it. you have update the package ?

**Comment by UrielCh** [comment]
check V0.2.0

**Comment by UrielCh** [comment]
V1.0.0 is out
