### ISSUE TITLE
Can this problem be solved. Add friends, please have some coffee. If it's inconvenient, please leave an ETH address

### ISSUE THREAD

**Issue by NameQuChen** [UrielCh/midjourney-client#9]
![239658260-42c1bc02-8174-4ca2-9433-e551a52d7e88](https://github.com/UrielCh/midjourney-client/assets/32125803/e1e4a86a-68c2-4864-8ed7-41495236cdf9)

**Comment by UrielCh** [comment]
lol

**Comment by UrielCh** [comment]
easy to fix, but... I appreciate mid-journey stuff, so I will not fix that.
